server:
  port: 8762
spring:
  application:
    name: springclouduser
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/gannan17?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: HL921124
  jpa:
    database: mysql
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://user:HL921124@localhost:8761/eureka
  instance:
    prefer-ip-address: true
